import { Button, Card, Body1, Caption1, Title1, Title3 } from '@fluentui/react-components';
import { ArrowRightRegular, ArrowUpRightRegular, CodeRegular, FolderOpenRegular, PersonRegular } from '@fluentui/react-icons';
import { useEffect, useState } from 'react';
import { api } from '../api';
import type { Profile, Project } from '../data/profile';
import { StatusBadge } from '../components/StatusBadge';

export function OverviewPage({ onNavigate }: { onNavigate: (path: string) => void }) { const [profile, setProfile] = useState<Profile | null>(null); const [projects, setProjects] = useState<Project[]>([]);
  useEffect(() => { Promise.all([api.getProfile(), api.getProjects()]).then(([nextProfile, nextProjects]) => { setProfile(nextProfile); setProjects(nextProjects); }); }, []);
  if (!profile) return <div className="loading-panel" aria-busy="true"><div /><div /><div /></div>;
  return <div className="page-stack">
    <section className="dashboard-header"><div><Caption1 className="eyebrow">GitHub · visão geral</Caption1><Title1>Dashboard de {profile.name}</Title1><Body1>{profile.summary}</Body1></div><div className="dashboard-status"><span /><div><strong>Sistema ativo</strong><Caption1>Dados sincronizados do GitHub</Caption1></div></div></section>
    <section className="metric-grid dashboard-metrics">{profile.metrics.map((metric, index) => <Card key={metric.label} className="metric-card"><span className="metric-number">0{index + 1}</span><strong>{metric.value}</strong><Caption1>{metric.label}</Caption1><Body1>{metric.detail}</Body1></Card>)}</section>
    <section className="dashboard-grid"><Card className="activity-dashboard"><div className="section-heading"><div><Caption1 className="eyebrow">Atividade</Caption1><Title3>Ritmo de contribuição</Title3></div><Caption1>Últimas 12 semanas</Caption1></div><div className="activity-chart" aria-label="Mapa de atividade"><div className="activity-days">{Array.from({ length: 84 }, (_, index) => <span key={index} className={`level-${(index * 7 + 3) % 5}`} />)}</div><div className="chart-labels"><Caption1>Menos</Caption1><Caption1>Maior atividade</Caption1></div></div></Card><Card className="focus-dashboard"><Caption1 className="eyebrow">Em foco</Caption1><Title3>Arquitetura, IA aplicada e plataformas</Title3><Body1>Frentes que organizam os projetos em desenvolvimento e os experimentos públicos.</Body1><Button appearance="subtle" icon={<CodeRegular />} onClick={() => onNavigate('/stack')}>Ver stack atual</Button></Card></section>
    <section><div className="section-heading"><div><Caption1 className="eyebrow">Repositórios recentes</Caption1><Title3><FolderOpenRegular /> Projetos em movimento</Title3></div><Button appearance="subtle" icon={<ArrowRightRegular />} iconPosition="after" onClick={() => onNavigate('/projects')}>Abrir catálogo</Button></div><div className="project-grid">{projects.slice(0, 3).map((project) => <Card key={project.name} className="project-card project-card-featured"><div className="project-topline"><StatusBadge status={project.status} /><FolderOpenRegular /></div><Title3>{project.name}</Title3><Body1>{project.focus}</Body1><div className="tech-list">{project.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div>{project.href && <a className="project-link" href={project.href} target="_blank" rel="noreferrer">Abrir repositório <ArrowUpRightRegular /></a>}</Card>)}</div></section>
    <section className="contact-panel"><div><Caption1 className="eyebrow">Vamos conversar</Caption1><Title3>Projetos reais, decisões de engenharia e aprendizado contínuo.</Title3><Body1>Disponível para trocar ideias sobre arquitetura, plataformas e IA aplicada.</Body1></div><div className="contact-actions"><Button appearance="primary" icon={<CodeRegular />} as="a" href="https://github.com/ebalbinodasilva" target="_blank">GitHub</Button><Button appearance="secondary" icon={<PersonRegular />} as="a" href="https://www.linkedin.com/in/evertonbalbinosilva" target="_blank">LinkedIn</Button></div></section>
  </div>;
}
