import { Button, Card, Body1, Caption1, Title1, Title3 } from '@fluentui/react-components';
import { ArrowRightRegular, ArrowUpRightRegular, CodeRegular, FolderOpenRegular, PersonRegular, SparkleRegular } from '@fluentui/react-icons';
import { useEffect, useState } from 'react';
import { api } from '../api';
import type { Profile, Project } from '../data/profile';
import { StatusBadge } from '../components/StatusBadge';

export function OverviewPage({ onNavigate }: { onNavigate: (path: string) => void }) { const [profile, setProfile] = useState<Profile | null>(null); const [projects, setProjects] = useState<Project[]>([]);
  useEffect(() => { Promise.all([api.getProfile(), api.getProjects()]).then(([nextProfile, nextProjects]) => { setProfile(nextProfile); setProjects(nextProjects); }); }, []);
  if (!profile) return <div className="loading-panel" aria-busy="true"><div /><div /><div /></div>;
  return <div className="page-stack">
    <section className="hero"><div className="hero-mesh" aria-hidden="true" /><div className="hero-layout"><div><Caption1 className="eyebrow">{profile.role}</Caption1><Title1>{profile.name}</Title1><Body1>{profile.summary}</Body1><div className="hero-actions"><Button appearance="primary" icon={<ArrowRightRegular />} onClick={() => onNavigate('/projects')}>Explorar projetos</Button><Button appearance="secondary" icon={<CodeRegular />} onClick={() => onNavigate('/stack')}>Stack e princípios</Button></div></div><aside className="hero-note"><SparkleRegular /><span>Construindo sistemas que permanecem claros quando a complexidade cresce.</span></aside></div></section>
    <section className="intro-grid"><div className="section-intro"><Caption1 className="eyebrow">Como eu atuo</Caption1><Title3>Engenharia conectada a decisões de produto.</Title3><Body1>Da arquitetura à operação, desenho caminhos práticos para times entregarem com mais autonomia, confiança e contexto.</Body1></div><div className="metric-grid">{profile.metrics.map((metric, index) => <Card key={metric.label} className="metric-card"><span className="metric-number">0{index + 1}</span><strong>{metric.value}</strong><Caption1>{metric.label}</Caption1><Body1>{metric.detail}</Body1></Card>)}</div></section>
    <section><div className="section-heading"><div><Caption1 className="eyebrow">Trabalho selecionado</Caption1><Title3><FolderOpenRegular /> Projetos em destaque</Title3></div><Button appearance="subtle" icon={<ArrowRightRegular />} iconPosition="after" onClick={() => onNavigate('/projects')}>Ver todos</Button></div><div className="project-grid">{projects.slice(0, 3).map((project) => <Card key={project.name} className="project-card project-card-featured"><div className="project-topline"><StatusBadge status={project.status} /><FolderOpenRegular /></div><Title3>{project.name}</Title3><Body1>{project.focus}</Body1><div className="tech-list">{project.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div>{project.href && <a className="project-link" href={project.href} target="_blank" rel="noreferrer">Ver no GitHub <ArrowUpRightRegular /></a>}</Card>)}</div></section>
    <section className="contact-panel"><div><Caption1 className="eyebrow">Vamos conversar</Caption1><Title3>Projetos reais, decisões de engenharia e aprendizado contínuo.</Title3><Body1>Disponível para trocar ideias sobre arquitetura, plataformas e IA aplicada.</Body1></div><div className="contact-actions"><Button appearance="primary" icon={<CodeRegular />} as="a" href="https://github.com/ebalbinodasilva" target="_blank">GitHub</Button><Button appearance="secondary" icon={<PersonRegular />} as="a" href="https://www.linkedin.com/in/evertonbalbinosilva" target="_blank">LinkedIn</Button></div></section>
  </div>;
}
